import { SeanceEmploiDuTemps } from '../types';

export const INITIAL_SEANCES: SeanceEmploiDuTemps[] = [
  // ==========================================
  // CLASSE ID 3: TERMINALE S1 (Sciences Exactes)
  // ==========================================
  // LUNDI
  {
    id: 101,
    classe_id: 3,
    classe_nom: 'Terminale S1',
    jour: 'LUNDI',
    heure_debut: '08:00',
    heure_fin: '10:00',
    matiere_nom: 'Mathématiques',
    enseignant_nom: 'M. Moussa Diop',
    salle: 'Salle C-201',
    couleur: 'blue',
    type: 'COURS',
    description: 'Analyse & Dérivation - Fonctions exponentielles et logarithmes',
    materiel_requis: 'Calculatrice scientifique, cahier grand format',
  },
  {
    id: 102,
    classe_id: 3,
    classe_nom: 'Terminale S1',
    jour: 'LUNDI',
    heure_debut: '10:15',
    heure_fin: '12:15',
    matiere_nom: 'Physique-Chimie',
    enseignant_nom: 'M. Jean Mendy',
    salle: 'Labo Sciences L-02',
    couleur: 'cyan',
    type: 'TP',
    description: 'Travaux Pratiques : Cinétique chimique & Titrage acido-basique',
    materiel_requis: 'Blouse blanche obligatoire, lunettes de protection',
  },
  {
    id: 103,
    classe_id: 3,
    classe_nom: 'Terminale S1',
    jour: 'LUNDI',
    heure_debut: '14:00',
    heure_fin: '16:00',
    matiere_nom: 'Sciences de la Vie et de la Terre (SVT)',
    enseignant_nom: 'Mme Fatimata Ba',
    salle: 'Salle Bio B-04',
    couleur: 'emerald',
    type: 'COURS',
    description: 'Génétique humaine et brassages chromosomiques',
    materiel_requis: 'Manuel SVT Terminale S, classeur',
  },
  {
    id: 104,
    classe_id: 3,
    classe_nom: 'Terminale S1',
    jour: 'LUNDI',
    heure_debut: '16:15',
    heure_fin: '18:00',
    matiere_nom: 'Anglais',
    enseignant_nom: 'M. Oumar Ndiaye',
    salle: 'Salle C-201',
    couleur: 'indigo',
    type: 'TD',
    description: 'Reading Comprehension & Scientific Vocabulary',
    materiel_requis: 'Dictionnaire bilingue recommandé',
  },

  // MARDI
  {
    id: 105,
    classe_id: 3,
    classe_nom: 'Terminale S1',
    jour: 'MARDI',
    heure_debut: '08:00',
    heure_fin: '10:00',
    matiere_nom: 'Physique-Chimie',
    enseignant_nom: 'M. Jean Mendy',
    salle: 'Salle C-201',
    couleur: 'cyan',
    type: 'COURS',
    description: 'Mécanique newtonienne et mouvements circulaires',
  },
  {
    id: 106,
    classe_id: 3,
    classe_nom: 'Terminale S1',
    jour: 'MARDI',
    heure_debut: '10:15',
    heure_fin: '12:15',
    matiere_nom: 'Mathématiques',
    enseignant_nom: 'M. Moussa Diop',
    salle: 'Salle C-201',
    couleur: 'blue',
    type: 'TD',
    description: 'Exercices dirigés : Suites numériques et limites',
  },
  {
    id: 107,
    classe_id: 3,
    classe_nom: 'Terminale S1',
    jour: 'MARDI',
    heure_debut: '14:00',
    heure_fin: '16:00',
    matiere_nom: 'Philosophie',
    enseignant_nom: 'M. Alioune Fall',
    salle: 'Salle C-201',
    couleur: 'purple',
    type: 'COURS',
    description: 'La Conscience et l\'Inconscient - Méthodologie de dissertation',
    materiel_requis: 'Recueil de textes philosophiques',
  },
  {
    id: 108,
    classe_id: 3,
    classe_nom: 'Terminale S1',
    jour: 'MARDI',
    heure_debut: '16:15',
    heure_fin: '18:00',
    matiere_nom: 'Informatique & Algorithmique',
    enseignant_nom: 'M. Patrick Toure',
    salle: 'Salle Info 1',
    couleur: 'blue',
    type: 'TP',
    description: 'Structures de données et programmation Python',
  },

  // MERCREDI
  {
    id: 109,
    classe_id: 3,
    classe_nom: 'Terminale S1',
    jour: 'MERCREDI',
    heure_debut: '08:00',
    heure_fin: '10:00',
    matiere_nom: 'Mathématiques',
    enseignant_nom: 'M. Moussa Diop',
    salle: 'Salle C-201',
    couleur: 'blue',
    type: 'COURS',
    description: 'Nombres complexes et géométrie plane',
  },
  {
    id: 110,
    classe_id: 3,
    classe_nom: 'Terminale S1',
    jour: 'MERCREDI',
    heure_debut: '10:15',
    heure_fin: '12:15',
    matiere_nom: 'Histoire-Géographie',
    enseignant_nom: 'Mme Salimata Diallo',
    salle: 'Salle C-201',
    couleur: 'amber',
    type: 'COURS',
    description: 'Les dynamiques de la mondialisation économique contemporaine',
  },

  // JEUDI
  {
    id: 111,
    classe_id: 3,
    classe_nom: 'Terminale S1',
    jour: 'JEUDI',
    heure_debut: '08:00',
    heure_fin: '10:00',
    matiere_nom: 'Sciences de la Vie et de la Terre (SVT)',
    enseignant_nom: 'Mme Fatimata Ba',
    salle: 'Labo Sciences L-02',
    couleur: 'emerald',
    type: 'TP',
    description: 'Observation microscopique et caryotypes',
    materiel_requis: 'Blouse de laboratoire',
  },
  {
    id: 112,
    classe_id: 3,
    classe_nom: 'Terminale S1',
    jour: 'JEUDI',
    heure_debut: '10:15',
    heure_fin: '12:15',
    matiere_nom: 'Français & Littérature',
    enseignant_nom: 'Mme Awa Koné',
    salle: 'Salle C-201',
    couleur: 'rose',
    type: 'COURS',
    description: 'Étude d\'œuvres africaines et francophones',
  },
  {
    id: 113,
    classe_id: 3,
    classe_nom: 'Terminale S1',
    jour: 'JEUDI',
    heure_debut: '14:00',
    heure_fin: '16:00',
    matiere_nom: 'Physique-Chimie',
    enseignant_nom: 'M. Jean Mendy',
    salle: 'Salle C-201',
    couleur: 'cyan',
    type: 'TD',
    description: 'Résolution de problèmes d\'électromagnétisme',
  },
  {
    id: 114,
    classe_id: 3,
    classe_nom: 'Terminale S1',
    jour: 'JEUDI',
    heure_debut: '16:15',
    heure_fin: '18:00',
    matiere_nom: 'Éducation Physique & Sportive (EPS)',
    enseignant_nom: 'M. Cheikh Sarr',
    salle: 'Terrain de sport',
    couleur: 'amber',
    type: 'COURS',
    description: 'Demi-fond et Basket-ball collectif',
    materiel_requis: 'Tenue de sport réglementaire Sukulu',
  },

  // VENDREDI
  {
    id: 115,
    classe_id: 3,
    classe_nom: 'Terminale S1',
    jour: 'VENDREDI',
    heure_debut: '08:00',
    heure_fin: '10:00',
    matiere_nom: 'Mathématiques',
    enseignant_nom: 'M. Moussa Diop',
    salle: 'Salle C-201',
    couleur: 'blue',
    type: 'EVALUATION',
    description: 'Devoir surveillé bimensuel - Épreuves type Bac',
  },
  {
    id: 116,
    classe_id: 3,
    classe_nom: 'Terminale S1',
    jour: 'VENDREDI',
    heure_debut: '10:15',
    heure_fin: '12:15',
    matiere_nom: 'Philosophie',
    enseignant_nom: 'M. Alioune Fall',
    salle: 'Salle C-201',
    couleur: 'purple',
    type: 'TD',
    description: 'Entraînement au commentaire de texte philosophique',
  },
  {
    id: 117,
    classe_id: 3,
    classe_nom: 'Terminale S1',
    jour: 'VENDREDI',
    heure_debut: '15:00',
    heure_fin: '17:00',
    matiere_nom: 'Anglais',
    enseignant_nom: 'M. Oumar Ndiaye',
    salle: 'Salle C-201',
    couleur: 'indigo',
    type: 'COURS',
    description: 'Oral debate and current affairs presentation',
  },

  // SAMEDI
  {
    id: 118,
    classe_id: 3,
    classe_nom: 'Terminale S1',
    jour: 'SAMEDI',
    heure_debut: '08:00',
    heure_fin: '10:00',
    matiere_nom: 'Soutien & Renforcement Math / PC',
    enseignant_nom: 'M. Moussa Diop',
    salle: 'Salle C-201',
    couleur: 'blue',
    type: 'TD',
    description: 'Séance de tutorat et révisions d\'annales du Baccalauréat',
  },
  {
    id: 119,
    classe_id: 3,
    classe_nom: 'Terminale S1',
    jour: 'SAMEDI',
    heure_debut: '10:15',
    heure_fin: '12:00',
    matiere_nom: 'Orientation Post-Bac & Mentorat',
    enseignant_nom: 'Mme Awa Koné',
    salle: 'Amphithéâtre A',
    couleur: 'rose',
    type: 'COURS',
    description: 'Présentation des filières d\'ingénieurs, médecine et universités',
  },

  // ==========================================
  // CLASSE ID 2: 3ème B (Collège - Classe de Mamadou Sow, fils d'Ibrahima Sow)
  // ==========================================
  // LUNDI
  {
    id: 201,
    classe_id: 2,
    classe_nom: '3ème B',
    jour: 'LUNDI',
    heure_debut: '08:00',
    heure_fin: '10:00',
    matiere_nom: 'Français',
    enseignant_nom: 'Mme Awa Koné',
    salle: 'Salle C-204',
    couleur: 'rose',
    type: 'COURS',
    description: 'Grammaire, dictée et préparation au Brevet des Collèges (BFEM)',
    materiel_requis: 'Cahier de français, livre de grammaire',
  },
  {
    id: 202,
    classe_id: 2,
    classe_nom: '3ème B',
    jour: 'LUNDI',
    heure_debut: '10:15',
    heure_fin: '12:15',
    matiere_nom: 'Mathématiques',
    enseignant_nom: 'M. Moussa Diop',
    salle: 'Salle C-204',
    couleur: 'blue',
    type: 'COURS',
    description: 'Théorème de Thalès et trigonométrie dans le triangle rectangle',
    materiel_requis: 'Matériel de géométrie (équerre, compas, rapporteur)',
  },
  {
    id: 203,
    classe_id: 2,
    classe_nom: '3ème B',
    jour: 'LUNDI',
    heure_debut: '14:00',
    heure_fin: '16:00',
    matiere_nom: 'Histoire-Géographie',
    enseignant_nom: 'Mme Salimata Diallo',
    salle: 'Salle C-204',
    couleur: 'amber',
    type: 'COURS',
    description: 'La Première Guerre mondiale et l\'Afrique au début du XXe siècle',
  },
  {
    id: 204,
    classe_id: 2,
    classe_nom: '3ème B',
    jour: 'LUNDI',
    heure_debut: '16:15',
    heure_fin: '18:00',
    matiere_nom: 'Anglais',
    enseignant_nom: 'M. Oumar Ndiaye',
    salle: 'Salle C-204',
    couleur: 'indigo',
    type: 'COURS',
    description: 'Past tenses and dialogue practice',
  },

  // MARDI
  {
    id: 205,
    classe_id: 2,
    classe_nom: '3ème B',
    jour: 'MARDI',
    heure_debut: '08:00',
    heure_fin: '10:00',
    matiere_nom: 'Sciences Physiques',
    enseignant_nom: 'M. Jean Mendy',
    salle: 'Labo Sciences L-01',
    couleur: 'cyan',
    type: 'TP',
    description: 'Circuits électriques et lois des tensions',
    materiel_requis: 'Blouse de protection',
  },
  {
    id: 206,
    classe_id: 2,
    classe_nom: '3ème B',
    jour: 'MARDI',
    heure_debut: '10:15',
    heure_fin: '12:15',
    matiere_nom: 'Sciences de la Vie et de la Terre (SVT)',
    enseignant_nom: 'Mme Fatimata Ba',
    salle: 'Salle C-204',
    couleur: 'emerald',
    type: 'COURS',
    description: 'Immunologie et défense de l\'organisme contre les microbes',
  },
  {
    id: 207,
    classe_id: 2,
    classe_nom: '3ème B',
    jour: 'MARDI',
    heure_debut: '14:00',
    heure_fin: '16:00',
    matiere_nom: 'Mathématiques',
    enseignant_nom: 'M. Moussa Diop',
    salle: 'Salle C-204',
    couleur: 'blue',
    type: 'TD',
    description: 'Calcul littéral et factorisation - Exercices d\'entraînement',
  },
  {
    id: 208,
    classe_id: 2,
    classe_nom: '3ème B',
    jour: 'MARDI',
    heure_debut: '16:15',
    heure_fin: '18:00',
    matiere_nom: 'Éducation Civique & Morale',
    enseignant_nom: 'Mme Salimata Diallo',
    salle: 'Salle C-204',
    couleur: 'amber',
    type: 'COURS',
    description: 'Les institutions républicaines et la citoyenneté responsable',
  },

  // MERCREDI
  {
    id: 209,
    classe_id: 2,
    classe_nom: '3ème B',
    jour: 'MERCREDI',
    heure_debut: '08:00',
    heure_fin: '10:00',
    matiere_nom: 'Éducation Physique & Sportive (EPS)',
    enseignant_nom: 'M. Cheikh Sarr',
    salle: 'Terrain de sport',
    couleur: 'amber',
    type: 'COURS',
    description: 'Gymnastique au sol et saut en hauteur',
    materiel_requis: 'Tenue sportive complète, bouteille d\'eau',
  },
  {
    id: 210,
    classe_id: 2,
    classe_nom: '3ème B',
    jour: 'MERCREDI',
    heure_debut: '10:15',
    heure_fin: '12:15',
    matiere_nom: 'Informatique',
    enseignant_nom: 'M. Patrick Toure',
    salle: 'Salle Info 2',
    couleur: 'blue',
    type: 'TP',
    description: 'Initiation au traitement de texte et recherche documentaire',
  },

  // JEUDI
  {
    id: 211,
    classe_id: 2,
    classe_nom: '3ème B',
    jour: 'JEUDI',
    heure_debut: '08:00',
    heure_fin: '10:00',
    matiere_nom: 'Français',
    enseignant_nom: 'Mme Awa Koné',
    salle: 'Salle C-204',
    couleur: 'rose',
    type: 'COURS',
    description: 'Lecture méthodique d\'un roman de Cheikh Hamidou Kane',
  },
  {
    id: 212,
    classe_id: 2,
    classe_nom: '3ème B',
    jour: 'JEUDI',
    heure_debut: '10:15',
    heure_fin: '12:15',
    matiere_nom: 'Mathématiques',
    enseignant_nom: 'M. Moussa Diop',
    salle: 'Salle C-204',
    couleur: 'blue',
    type: 'COURS',
    description: 'Équations et inéquations du premier degré à une inconnue',
  },
  {
    id: 213,
    classe_id: 2,
    classe_nom: '3ème B',
    jour: 'JEUDI',
    heure_debut: '14:00',
    heure_fin: '16:00',
    matiere_nom: 'Arts Plastiques / Dessin',
    enseignant_nom: 'Mme Mariam Sow',
    salle: 'Atelier d\'Arts',
    couleur: 'purple',
    type: 'TP',
    description: 'Perspective cavalière et ombres portées',
    materiel_requis: 'Feuilles Canson, crayons de couleur',
  },
  {
    id: 214,
    classe_id: 2,
    classe_nom: '3ème B',
    jour: 'JEUDI',
    heure_debut: '16:15',
    heure_fin: '18:00',
    matiere_nom: 'Espagnol / Arabe (LV2)',
    enseignant_nom: 'M. Carlos Gomez',
    salle: 'Salle C-204',
    couleur: 'teal',
    type: 'COURS',
    description: 'Vocabulario básico de la familia y descripción física',
  },

  // VENDREDI
  {
    id: 215,
    classe_id: 2,
    classe_nom: '3ème B',
    jour: 'VENDREDI',
    heure_debut: '08:00',
    heure_fin: '10:00',
    matiere_nom: 'Sciences Physiques',
    enseignant_nom: 'M. Jean Mendy',
    salle: 'Salle C-204',
    couleur: 'cyan',
    type: 'COURS',
    description: 'Masse volumique et pression des fluides',
  },
  {
    id: 216,
    classe_id: 2,
    classe_nom: '3ème B',
    jour: 'VENDREDI',
    heure_debut: '10:15',
    heure_fin: '12:15',
    matiere_nom: 'Histoire-Géographie',
    enseignant_nom: 'Mme Salimata Diallo',
    salle: 'Salle C-204',
    couleur: 'amber',
    type: 'TD',
    description: 'Étude de documents cartographiques et graphiques',
  },
  {
    id: 217,
    classe_id: 2,
    classe_nom: '3ème B',
    jour: 'VENDREDI',
    heure_debut: '15:00',
    heure_fin: '17:00',
    matiere_nom: 'Français - Devoir',
    enseignant_nom: 'Mme Awa Koné',
    salle: 'Salle C-204',
    couleur: 'rose',
    type: 'EVALUATION',
    description: 'Contrôle continu : Rédaction et compréhension de texte',
  },

  // SAMEDI
  {
    id: 218,
    classe_id: 2,
    classe_nom: '3ème B',
    jour: 'SAMEDI',
    heure_debut: '08:00',
    heure_fin: '10:00',
    matiere_nom: 'Soutien Préparation BFEM / Brevet',
    enseignant_nom: 'M. Moussa Diop',
    salle: 'Salle C-204',
    couleur: 'blue',
    type: 'TD',
    description: 'Révision méthodologique des annales d\'examens',
  },
  {
    id: 219,
    classe_id: 2,
    classe_nom: '3ème B',
    jour: 'SAMEDI',
    heure_debut: '10:15',
    heure_fin: '12:00',
    matiere_nom: 'Club Lecture & Débats',
    enseignant_nom: 'Mme Awa Koné',
    salle: 'Médiathèque',
    couleur: 'purple',
    type: 'COURS',
    description: 'Atelier d\'éloquence et prise de parole en public',
  },

  // ==========================================
  // CLASSE ID 1: 6ème A
  // ==========================================
  {
    id: 301,
    classe_id: 1,
    classe_nom: '6ème A',
    jour: 'LUNDI',
    heure_debut: '08:00',
    heure_fin: '10:00',
    matiere_nom: 'Français',
    enseignant_nom: 'Mme Awa Koné',
    salle: 'Salle C-101',
    couleur: 'rose',
    type: 'COURS',
  },
  {
    id: 302,
    classe_id: 1,
    classe_nom: '6ème A',
    jour: 'LUNDI',
    heure_debut: '10:15',
    heure_fin: '12:15',
    matiere_nom: 'Mathématiques',
    enseignant_nom: 'M. Jean Mendy',
    salle: 'Salle C-101',
    couleur: 'blue',
    type: 'COURS',
  },
  {
    id: 303,
    classe_id: 1,
    classe_nom: '6ème A',
    jour: 'MARDI',
    heure_debut: '08:00',
    heure_fin: '10:00',
    matiere_nom: 'SVT',
    enseignant_nom: 'Mme Fatimata Ba',
    salle: 'Salle C-101',
    couleur: 'emerald',
    type: 'COURS',
  },
  {
    id: 304,
    classe_id: 1,
    classe_nom: '6ème A',
    jour: 'MARDI',
    heure_debut: '10:15',
    heure_fin: '12:15',
    matiere_nom: 'Anglais',
    enseignant_nom: 'M. Oumar Ndiaye',
    salle: 'Salle C-101',
    couleur: 'indigo',
    type: 'COURS',
  },
  {
    id: 305,
    classe_id: 1,
    classe_nom: '6ème A',
    jour: 'JEUDI',
    heure_debut: '08:00',
    heure_fin: '10:00',
    matiere_nom: 'Histoire-Géo',
    enseignant_nom: 'Mme Salimata Diallo',
    salle: 'Salle C-101',
    couleur: 'amber',
    type: 'COURS',
  },
  {
    id: 306,
    classe_id: 1,
    classe_nom: '6ème A',
    jour: 'VENDREDI',
    heure_debut: '08:00',
    heure_fin: '10:00',
    matiere_nom: 'EPS',
    enseignant_nom: 'M. Cheikh Sarr',
    salle: 'Terrain de sport',
    couleur: 'amber',
    type: 'COURS',
  },

  // ==========================================
  // CLASSE ID 4: Terminale L1
  // ==========================================
  {
    id: 401,
    classe_id: 4,
    classe_nom: 'Terminale L1',
    jour: 'LUNDI',
    heure_debut: '08:00',
    heure_fin: '10:00',
    matiere_nom: 'Littérature & Français',
    enseignant_nom: 'Mme Awa Koné',
    salle: 'Salle L-105',
    couleur: 'rose',
    type: 'COURS',
  },
  {
    id: 402,
    classe_id: 4,
    classe_nom: 'Terminale L1',
    jour: 'LUNDI',
    heure_debut: '10:15',
    heure_fin: '12:15',
    matiere_nom: 'Philosophie',
    enseignant_nom: 'M. Alioune Fall',
    salle: 'Salle L-105',
    couleur: 'purple',
    type: 'COURS',
  },
  {
    id: 403,
    classe_id: 4,
    classe_nom: 'Terminale L1',
    jour: 'MARDI',
    heure_debut: '08:00',
    heure_fin: '10:00',
    matiere_nom: 'Histoire-Géographie',
    enseignant_nom: 'Mme Salimata Diallo',
    salle: 'Salle L-105',
    couleur: 'amber',
    type: 'COURS',
  },
  {
    id: 404,
    classe_id: 4,
    classe_nom: 'Terminale L1',
    jour: 'MERCREDI',
    heure_debut: '08:00',
    heure_fin: '10:00',
    matiere_nom: 'Anglais Renforcé',
    enseignant_nom: 'M. Oumar Ndiaye',
    salle: 'Salle L-105',
    couleur: 'indigo',
    type: 'COURS',
  },
];
