import {
  User,
  Filiere,
  Classe,
  Inscription,
  Evaluation,
  Note,
  Absence,
  Paiement,
  DocumentScolaire,
  DashboardStats,
} from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 1,
    username: 'admin',
    email: 'direction@sukulu.edu',
    first_name: 'Amadou',
    last_name: 'Kouassi',
    role: 'ADMIN',
    phone: '+225 07 08 12 34 56',
    address: 'Cocody Cité des Cadres, Abidjan',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250',
    is_active: true,
    date_joined: '2024-01-10',
    matricule: 'ADM-2024-001',
  },
  {
    id: 2,
    username: 'prof_diop',
    email: 'm.diop@sukulu.edu',
    first_name: 'Moussa',
    last_name: 'Diop',
    role: 'ENSEIGNANT',
    phone: '+221 77 450 88 12',
    address: 'Plateau, Dakar',
    specialite: 'Mathématiques & Physique',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=250',
    is_active: true,
    date_joined: '2023-09-01',
    matricule: 'ENS-2023-012',
  },
  {
    id: 3,
    username: 'prof_kone',
    email: 'a.kone@sukulu.edu',
    first_name: 'Awa',
    last_name: 'Koné',
    role: 'ENSEIGNANT',
    phone: '+225 05 44 90 11 22',
    address: 'Marcory, Abidjan',
    specialite: 'Français & Littérature',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=250',
    is_active: true,
    date_joined: '2023-09-01',
    matricule: 'ENS-2023-015',
  },
  {
    id: 12,
    username: 'educateur_ndiaye',
    email: 'educateur@sukulu.sn',
    first_name: 'Babacar',
    last_name: 'Ndiaye',
    role: 'EDUCATEUR',
    phone: '+221 77 555 12 34',
    address: 'Almadies, Dakar',
    specialite: 'Vie Scolaire & Suivi des Élèves',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=250',
    is_active: true,
    date_joined: '2023-09-01',
    matricule: 'EDU-2023-001',
  },
  {
    id: 4,
    username: 'eleve_fatou',
    email: 'fatou.sow@sukulu.edu',
    first_name: 'Fatou',
    last_name: 'Sow',
    role: 'ELEVE',
    phone: '+221 78 123 45 67',
    address: 'Fann Résidence, Dakar',
    matricule: 'SKL-2024-0089',
    classe_id: 3,
    classe_nom: 'Terminale S1',
    filiere_nom: 'Sciences Exactes',
    avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&q=80&w=250',
    is_active: true,
    date_joined: '2024-09-10',
  },
  {
    id: 5,
    username: 'eleve_kofi',
    email: 'kofi.mensah@sukulu.edu',
    first_name: 'Kofi',
    last_name: 'Mensah',
    role: 'ELEVE',
    phone: '+225 01 22 33 44 55',
    address: 'Yopougon, Abidjan',
    matricule: 'SKL-2024-0102',
    classe_id: 2,
    classe_nom: '3ème B',
    filiere_nom: 'Enseignement Général',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=250',
    is_active: true,
    date_joined: '2024-09-12',
  },
  {
    id: 7,
    username: 'eleve_mamadou',
    email: 'mamadou.sow@sukulu.edu',
    first_name: 'Mamadou',
    last_name: 'Sow',
    role: 'ELEVE',
    phone: '+221 77 123 99 88',
    address: 'Fann Résidence, Dakar',
    matricule: 'SKL-2024-0091',
    classe_id: 2,
    classe_nom: '3ème B',
    filiere_nom: 'Enseignement Général',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=250',
    is_active: true,
    date_joined: '2024-09-10',
  },
  {
    id: 8,
    username: 'eleve_mariama',
    email: 'mariama.cisse@sukulu.edu',
    first_name: 'Mariama',
    last_name: 'Cissé',
    role: 'ELEVE',
    phone: '+225 07 88 77 66',
    address: 'Cocody, Abidjan',
    matricule: 'SKL-2024-0105',
    classe_id: 2,
    classe_nom: '3ème B',
    filiere_nom: 'Enseignement Général',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&q=80&w=250',
    is_active: true,
    date_joined: '2024-09-12',
  },
  {
    id: 9,
    username: 'eleve_ousmane',
    email: 'ousmane.traore@sukulu.edu',
    first_name: 'Ousmane',
    last_name: 'Traoré',
    role: 'ELEVE',
    phone: '+225 05 33 22 11',
    address: 'Abobo, Abidjan',
    matricule: 'SKL-2024-0108',
    classe_id: 2,
    classe_nom: '3ème B',
    filiere_nom: 'Enseignement Général',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=250',
    is_active: true,
    date_joined: '2024-09-12',
  },
  {
    id: 10,
    username: 'eleve_aminata',
    email: 'aminata.ndiaye@sukulu.edu',
    first_name: 'Aminata',
    last_name: 'Ndiaye',
    role: 'ELEVE',
    phone: '+221 70 888 99 00',
    address: 'Ngor, Dakar',
    matricule: 'SKL-2024-0145',
    classe_id: 4,
    classe_nom: 'Terminale L1',
    filiere_nom: 'Lettres & Langues',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=250',
    is_active: true,
    date_joined: '2024-09-10',
  },
  {
    id: 11,
    username: 'eleve_salimata',
    email: 'salimata.bamba@sukulu.edu',
    first_name: 'Salimata',
    last_name: 'Bamba',
    role: 'ELEVE',
    phone: '+225 01 99 88 77',
    address: 'Treichville, Abidjan',
    matricule: 'SKL-2024-0050',
    classe_id: 1,
    classe_nom: '6ème A',
    filiere_nom: 'Enseignement Général',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=250',
    is_active: true,
    date_joined: '2024-09-15',
  },
  {
    id: 6,
    username: 'parent_sow',
    email: 'ibrahima.sow@gmail.com',
    first_name: 'Ibrahima',
    last_name: 'Sow',
    role: 'PARENT',
    phone: '+221 77 600 11 22',
    address: 'Fann Résidence, Dakar',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=250',
    is_active: true,
    date_joined: '2024-09-10',
    children_ids: [7, 4], // 7 = Mamadou Sow (Fils, 3ème B), 4 = Fatou Sow (Fille, Terminale S1)
  },
];

export const INITIAL_FILIERES: Filiere[] = [
  {
    id: 1,
    code: 'GEN',
    nom: 'Enseignement Général',
    description: 'Tronc commun et premier cycle collège/lycée',
    created_at: '2023-08-15',
  },
  {
    id: 2,
    code: 'SCI',
    nom: 'Sciences Exactes & Expérimentales',
    description: 'Série S (Mathématiques, Physique-Chimie, SVT)',
    created_at: '2023-08-15',
  },
  {
    id: 3,
    code: 'LIT',
    nom: 'Lettres & Langues',
    description: 'Série A / L (Littérature, Philosophie, Langues vivantes)',
    created_at: '2023-08-15',
  },
  {
    id: 4,
    code: 'ECO',
    nom: 'Sciences Économiques & Gestion',
    description: 'Série G / STE (Comptabilité, Gestion, Économie)',
    created_at: '2023-08-15',
  },
];

export const INITIAL_CLASSES: Classe[] = [
  {
    id: 1,
    code: '6A',
    nom: '6ème A',
    niveau: 'Collège',
    filiere_id: 1,
    filiere_nom: 'Enseignement Général',
    enseignant_titulaire_id: 3,
    enseignant_titulaire_nom: 'Mme Awa Koné',
    salle: 'Salle C-101',
    effectif_max: 45,
    effectif_actuel: 40,
    frais_scolarite: 350000,
  },
  {
    id: 2,
    code: '3B',
    nom: '3ème B',
    niveau: 'Collège',
    filiere_id: 1,
    filiere_nom: 'Enseignement Général',
    enseignant_titulaire_id: 2,
    enseignant_titulaire_nom: 'M. Moussa Diop',
    salle: 'Salle C-204',
    effectif_max: 40,
    effectif_actuel: 38,
    frais_scolarite: 420000,
  },
  {
    id: 3,
    code: 'TS1',
    nom: 'Terminale S1',
    niveau: 'Lycée',
    filiere_id: 2,
    filiere_nom: 'Sciences Exactes & Expérimentales',
    enseignant_titulaire_id: 2,
    enseignant_titulaire_nom: 'M. Moussa Diop',
    salle: 'Labo Sciences L-02',
    effectif_max: 35,
    effectif_actuel: 32,
    frais_scolarite: 550000,
  },
  {
    id: 4,
    code: 'TL1',
    nom: 'Terminale L1',
    niveau: 'Lycée',
    filiere_id: 3,
    filiere_nom: 'Lettres & Langues',
    enseignant_titulaire_id: 3,
    enseignant_titulaire_nom: 'Mme Awa Koné',
    salle: 'Salle L-105',
    effectif_max: 40,
    effectif_actuel: 36,
    frais_scolarite: 500000,
  },
];

export const INITIAL_INSCRIPTIONS: Inscription[] = [
  {
    id: 1,
    matricule: 'SKL-2024-0089',
    eleve_id: 4,
    eleve_nom: 'Sow',
    eleve_prenom: 'Fatou',
    eleve_email: 'fatou.sow@sukulu.edu',
    classe_id: 3,
    classe_nom: 'Terminale S1',
    filiere_nom: 'Sciences Exactes & Expérimentales',
    annee_academique: '2025-2026',
    date_inscription: '2025-09-02',
    statut: 'VALIDE',
    frais_totaux: 550000,
    frais_payes: 550000,
    mode_paiement: 'Mobile Money (Orange)',
    parent_nom: 'Ibrahima Sow',
    parent_telephone: '+221 77 600 11 22',
    documents_fournis: {
      acte_naissance: true,
      bulletin_anterieur: true,
      photo_identite: true,
    },
  },
  {
    id: 2,
    matricule: 'SKL-2024-0102',
    eleve_id: 5,
    eleve_nom: 'Mensah',
    eleve_prenom: 'Kofi',
    eleve_email: 'kofi.mensah@sukulu.edu',
    classe_id: 2,
    classe_nom: '3ème B',
    filiere_nom: 'Enseignement Général',
    annee_academique: '2025-2026',
    date_inscription: '2025-09-05',
    statut: 'VALIDE',
    frais_totaux: 420000,
    frais_payes: 250000,
    mode_paiement: 'Espèces',
    parent_nom: 'Kwadwo Mensah',
    parent_telephone: '+225 07 11 22 33 44',
    documents_fournis: {
      acte_naissance: true,
      bulletin_anterieur: true,
      photo_identite: true,
    },
  },
  {
    id: 3,
    matricule: 'SKL-2024-0145',
    eleve_id: 10,
    eleve_nom: 'Ndiaye',
    eleve_prenom: 'Aminata',
    eleve_email: 'aminata.n@gmail.com',
    classe_id: 4,
    classe_nom: 'Terminale L1',
    filiere_nom: 'Lettres & Langues',
    annee_academique: '2025-2026',
    date_inscription: '2025-09-10',
    statut: 'EN_ATTENTE',
    frais_totaux: 500000,
    frais_payes: 100000,
    mode_paiement: 'Carte Bancaire',
    parent_nom: 'Ousmane Ndiaye',
    parent_telephone: '+221 70 888 99 00',
    documents_fournis: {
      acte_naissance: true,
      bulletin_anterieur: false,
      photo_identite: true,
    },
  },
];

export const INITIAL_EVALUATIONS: Evaluation[] = [
  {
    id: 1,
    titre: 'Devoir de Synthèse - Algèbre & Analyse',
    type: 'DEVOIR',
    matiere_id: 1,
    matiere_nom: 'Mathématiques',
    classe_id: 3,
    classe_nom: 'Terminale S1',
    date_eval: '2025-10-15',
    coefficient: 4,
    note_max: 20,
    trimestre: 'TRIMESTRE_1',
  },
  {
    id: 2,
    titre: 'Examen de Chimie Organique',
    type: 'EXAMEN',
    matiere_id: 2,
    matiere_nom: 'Physique-Chimie',
    classe_id: 3,
    classe_nom: 'Terminale S1',
    date_eval: '2025-11-02',
    coefficient: 3,
    note_max: 20,
    trimestre: 'TRIMESTRE_1',
  },
  {
    id: 3,
    titre: 'Dissertation Littéraire - Le Roman Africain',
    type: 'DEVOIR',
    matiere_id: 3,
    matiere_nom: 'Français',
    classe_id: 4,
    classe_nom: 'Terminale L1',
    date_eval: '2025-10-20',
    coefficient: 5,
    note_max: 20,
    trimestre: 'TRIMESTRE_1',
  },
];

export const INITIAL_NOTES: Note[] = [
  {
    id: 1,
    evaluation_id: 1,
    evaluation_titre: 'Devoir de Synthèse - Algèbre',
    eleve_id: 4,
    eleve_nom: 'Fatou Sow',
    eleve_matricule: 'SKL-2024-0089',
    matiere_nom: 'Mathématiques',
    valeur: 17.5,
    coefficient: 4,
    appreciation: 'Excellent travail, très bonne rigueur démonstrative.',
    trimestre: 'TRIMESTRE_1',
    date_saisie: '2025-10-16',
  },
  {
    id: 2,
    evaluation_id: 2,
    evaluation_titre: 'Examen de Chimie Organique',
    eleve_id: 4,
    eleve_nom: 'Fatou Sow',
    eleve_matricule: 'SKL-2024-0089',
    matiere_nom: 'Physique-Chimie',
    valeur: 16.0,
    coefficient: 3,
    appreciation: 'Très bien assimilé.',
    trimestre: 'TRIMESTRE_1',
    date_saisie: '2025-11-03',
  },
  {
    id: 3,
    evaluation_id: 1,
    evaluation_titre: 'Devoir de Synthèse - Algèbre',
    eleve_id: 5,
    eleve_nom: 'Kofi Mensah',
    eleve_matricule: 'SKL-2024-0102',
    matiere_nom: 'Mathématiques',
    valeur: 13.5,
    coefficient: 3,
    appreciation: 'Bonne compréhension globale, attention aux étourderies.',
    trimestre: 'TRIMESTRE_1',
    date_saisie: '2025-10-16',
  },
];

export const INITIAL_ABSENCES: Absence[] = [
  {
    id: 1,
    eleve_id: 5,
    eleve_nom: 'Kofi Mensah',
    eleve_matricule: 'SKL-2024-0102',
    classe_id: 2,
    classe_nom: '3ème B',
    date_absence: '2025-10-22',
    type: 'ABSENCE',
    duree_heures: 2,
    matiere_nom: 'Histoire-Géographie',
    statut: 'JUSTIFIE',
    motif: 'Rendez-vous médical certifié.',
    justificatif_url: 'certificat_medical.pdf',
    trimestre: 'TRIMESTRE_1',
  },
  {
    id: 2,
    eleve_id: 4,
    eleve_nom: 'Fatou Sow',
    eleve_matricule: 'SKL-2024-0089',
    classe_id: 3,
    classe_nom: 'Terminale S1',
    date_absence: '2025-11-05',
    type: 'RETARD',
    duree_heures: 1,
    matiere_nom: 'Mathématiques',
    statut: 'NON_JUSTIFIE',
    motif: 'Embouteillage important en ville.',
    trimestre: 'TRIMESTRE_1',
  },
  {
    id: 3,
    eleve_id: 9,
    eleve_nom: 'Ousmane Traoré',
    eleve_matricule: 'SKL-2024-0108',
    classe_id: 2,
    classe_nom: '3ème B',
    date_absence: '2025-11-12',
    type: 'RETARD',
    duree_heures: 1,
    matiere_nom: 'Mathématiques',
    statut: 'NON_JUSTIFIE',
    motif: 'Arrivée tardive au 1er cours (15 min).',
    trimestre: 'TRIMESTRE_1',
  },
  {
    id: 4,
    eleve_id: 7,
    eleve_nom: 'Mamadou Bah',
    eleve_matricule: 'SKL-2024-0091',
    classe_id: 3,
    classe_nom: 'Terminale S1',
    date_absence: '2025-11-18',
    type: 'ABSENCE',
    duree_heures: 4,
    matiere_nom: 'Physique-Chimie',
    statut: 'JUSTIFIE',
    motif: 'Convocation sportive académique.',
    trimestre: 'TRIMESTRE_1',
  },
  {
    id: 5,
    eleve_id: 5,
    eleve_nom: 'Kofi Mensah',
    eleve_matricule: 'SKL-2024-0102',
    classe_id: 2,
    classe_nom: '3ème B',
    date_absence: '2026-01-14',
    type: 'RETARD',
    duree_heures: 1,
    matiere_nom: 'Français & Littérature',
    statut: 'NON_JUSTIFIE',
    motif: 'Panne de transport scolaire.',
    trimestre: 'TRIMESTRE_2',
  },
  {
    id: 6,
    eleve_id: 4,
    eleve_nom: 'Fatou Sow',
    eleve_matricule: 'SKL-2024-0089',
    classe_id: 3,
    classe_nom: 'Terminale S1',
    date_absence: '2026-02-02',
    type: 'RETARD',
    duree_heures: 1,
    matiere_nom: 'SVT (Sciences de la Vie)',
    statut: 'JUSTIFIE',
    motif: 'Retard de train de banlieue.',
    trimestre: 'TRIMESTRE_2',
  },
  {
    id: 7,
    eleve_id: 9,
    eleve_nom: 'Ousmane Traoré',
    eleve_matricule: 'SKL-2024-0108',
    classe_id: 2,
    classe_nom: '3ème B',
    date_absence: '2026-02-20',
    type: 'ABSENCE',
    duree_heures: 3,
    matiere_nom: 'Anglais',
    statut: 'EN_ATTENTE',
    motif: 'Raison familiale en cours de justification.',
    trimestre: 'TRIMESTRE_2',
  },
  {
    id: 8,
    eleve_id: 5,
    eleve_nom: 'Kofi Mensah',
    eleve_matricule: 'SKL-2024-0102',
    classe_id: 2,
    classe_nom: '3ème B',
    date_absence: '2026-04-10',
    type: 'RETARD',
    duree_heures: 1,
    matiere_nom: 'Physique-Chimie',
    statut: 'NON_JUSTIFIE',
    motif: 'Avertissement verbal prof.',
    trimestre: 'TRIMESTRE_3',
  },
];

export const INITIAL_PAIEMENTS: Paiement[] = [
  {
    id: 1,
    reference_recu: 'REC-2025-0891',
    eleve_id: 4,
    eleve_nom: 'Fatou Sow',
    eleve_matricule: 'SKL-2024-0089',
    classe_nom: 'Terminale S1',
    tranche: 'Frais de scolarité - Totalité Annuelle',
    montant: 550000,
    frais_totaux: 550000,
    mode_paiement: 'MOBILE_MONEY',
    statut: 'PAYE',
    date_paiement: '2025-09-02',
    annee_academique: '2025-2026',
    effectue_par: 'Ibrahima Sow (Parent)',
  },
  {
    id: 2,
    reference_recu: 'REC-2025-0942',
    eleve_id: 5,
    eleve_nom: 'Kofi Mensah',
    eleve_matricule: 'SKL-2024-0102',
    classe_nom: '3ème B',
    tranche: 'Tranche 1 (Inscription & Acompte)',
    montant: 250000,
    frais_totaux: 420000,
    mode_paiement: 'ESPECES',
    statut: 'PARTIEL',
    date_paiement: '2025-09-05',
    annee_academique: '2025-2026',
    effectue_par: 'Kwadwo Mensah (Parent)',
  },
];

export const INITIAL_DOCUMENTS: DocumentScolaire[] = [
  {
    id: 1,
    reference: 'BUL-2025-T1-0089',
    type: 'BULLETIN',
    titre: 'Bulletin Trimestriel de Notes - T1',
    eleve_id: 4,
    eleve_nom: 'Fatou Sow',
    eleve_matricule: 'SKL-2024-0089',
    classe_nom: 'Terminale S1',
    annee_academique: '2025-2026',
    date_generation: '2025-12-15',
    trimestre: 'TRIMESTRE_1',
    metadata: {
      moyenne_generale: 16.8,
      rang: '1er / 32',
      decision: 'Tableau d\'Honneur avec Félicitations du Conseil',
    },
  },
  {
    id: 2,
    reference: 'CERT-2025-0044',
    type: 'CERTIFICAT_SCOLARITE',
    titre: 'Certificat de Scolarité Officiel',
    eleve_id: 4,
    eleve_nom: 'Fatou Sow',
    eleve_matricule: 'SKL-2024-0089',
    classe_nom: 'Terminale S1',
    annee_academique: '2025-2026',
    date_generation: '2025-09-10',
  },
  {
    id: 3,
    reference: 'RECU-2025-0891',
    type: 'RECU_PAIEMENT',
    titre: 'Reçu de Paiement Scolarité #REC-2025-0891',
    eleve_id: 4,
    eleve_nom: 'Fatou Sow',
    eleve_matricule: 'SKL-2024-0089',
    classe_nom: 'Terminale S1',
    annee_academique: '2025-2026',
    date_generation: '2025-09-02',
    metadata: {
      montant: '550 000 FCFA',
      mode: 'Mobile Money (Orange)',
      statut: 'Solder intégralement',
    },
  },
];

export const DASHBOARD_STATS: DashboardStats = {
  total_eleves: 485,
  total_enseignants: 34,
  total_classes: 16,
  total_filieres: 4,
  taux_recouvrement: 84.5,
  montant_total_recouvre: 184500000, // FCFA
  absences_aujourdhui: 6,
  moyenne_generale_ecole: 14.2,
  prochains_examens: 3,
};
